In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np

In [2]:
df = pd.read_csv('ai4i2020.csv')

In [3]:
df.head(10)

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   
5    6     M14865    M                298.1                    308.6   
6    7     L47186    L                298.1                    308.6   
7    8     L47187    L                298.1                    308.6   
8    9     M14868    M                298.3                    308.7   
9   10     M14869    M                298.5                    309.0   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  TWF  \
0                    1551         42.8                0                0    0   
1                    1408         46.3                3                0    0   
2                    1498         49.4                5                0    0   
3                    1433         39.5                7                0    0   
4                    1408         40.0                9                0    0   
5                    1425         41.9               11                0    0   
6                    1558         42.4               14                0    0   
7                    1527         40.2               16                0    0   
8                    1667         28.6               18                0    0   
9                    1741         28.0               21                0    0   

   HDF  PWF  OSF  RNF  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0  
5    0    0    0    0  
6    0    0    0    0  
7    0    0    0    0  
8    0    0    0    0  
9    0    0    0    0

In [4]:
df.describe()

UDI  Air temperature [K]  Process temperature [K]  \
count  10000.00000         10000.000000             10000.000000   
mean    5000.50000           300.004930               310.005560   
std     2886.89568             2.000259                 1.483734   
min        1.00000           295.300000               305.700000   
25%     2500.75000           298.300000               308.800000   
50%     5000.50000           300.100000               310.100000   
75%     7500.25000           301.500000               311.100000   
max    10000.00000           304.500000               313.800000   

       Rotational speed [rpm]   Torque [Nm]  Tool wear [min]  Machine failure  \
count            10000.000000  10000.000000     10000.000000     10000.000000   
mean              1538.776100     39.986910       107.951000         0.033900   
std                179.284096      9.968934        63.654147         0.180981   
min               1168.000000      3.800000         0.000000         0.000000   
25%               1423.000000     33.200000        53.000000         0.000000   
50%               1503.000000     40.100000       108.000000         0.000000   
75%               1612.000000     46.800000       162.000000         0.000000   
max               2886.000000     76.600000       253.000000         1.000000   

                TWF           HDF           PWF           OSF          RNF  
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.00000  
mean       0.004600      0.011500      0.009500      0.009800      0.00190  
std        0.067671      0.106625      0.097009      0.098514      0.04355  
min        0.000000      0.000000      0.000000      0.000000      0.00000  
25%        0.000000      0.000000      0.000000      0.000000      0.00000  
50%        0.000000      0.000000      0.000000      0.000000      0.00000  
75%        0.000000      0.000000      0.000000      0.000000      0.00000  
max        1.000000      1.000000      1.000000      1.000000      1.00000

In [5]:
pf=ProfileReport(df)

In [6]:
pf.to_widgets()

In [ ]:
# From the above profile report
#the data in  the target variable or label(Air temperature) and independent parameter, process temperature are higly correlated
#But the other independent variables are also highly correlated with each other. 
#So this data suffers from Multicollinearity among the dependent features.
# The requirement that the independent features should be non correlated fails for this dataset.
#So, ideally, the Linear regression may not be the best option to model the data


In [ ]:
# Choosing the Air temperature and the process temperature, as they are higly correlated

#Trying to linear regress or do best fit for the above two features.

In [13]:
df.dtypes

UDI                          int64
Product ID                  object
Type                        object
Air temperature [K]        float64
Process temperature [K]    float64
Rotational speed [rpm]       int64
Torque [Nm]                float64
Tool wear [min]              int64
Machine failure              int64
TWF                          int64
HDF                          int64
PWF                          int64
OSF                          int64
RNF                          int64
dtype: object

In [32]:
proc_temp=df.iloc[0: ,4:5]

In [33]:
proc_temp

Process temperature [K]
0                       308.6
1                       308.7
2                       308.5
3                       308.6
4                       308.7
...                       ...
9995                    308.4
9996                    308.4
9997                    308.6
9998                    308.7
9999                    308.7

[10000 rows x 1 columns]

In [34]:
air_temp=df.iloc[0: ,3:4]

In [35]:
air_temp

Air temperature [K]
0                   298.1
1                   298.2
2                   298.1
3                   298.2
4                   298.2
...                   ...
9995                298.8
9996                298.9
9997                299.0
9998                299.0
9999                299.0

[10000 rows x 1 columns]

In [36]:
# Let us say our relation is
# air_temp(y)=m*proc_temp(x)+c
#m and c are parameters we need to optimize

In [37]:
from sklearn.linear_model import LinearRegression
linear=LinearRegression()

In [38]:
linear.fit(proc_temp,air_temp)

LinearRegression()

In [39]:
linear.intercept_
#This is the y- intercept i.e value of 'c' in the equation 'air_temp(y)=m*proc_temp(x)+c'

array([-66.14315172])

In [40]:
linear.coef_
#This is the slope i.e value of 'm' in the equation 'air_temp(y)=m*proc_temp(x)+c'

array([[1.18110166]])

In [41]:
# so the model describing the relation between the air temperature and process temperature is as foillows:
#air_temp=1.1811*proc_temp-66.143

In [43]:
new_file='lin_pred_maint.sav'
pickle.dump(linear,open(new_file,'wb'))

In [44]:
linear.predict([[450]])
#If we consider the value of process temp as 450 K, the air temp as per the model is 465.35 K

array([[465.35259556]])

In [45]:
linear.predict([[309.2]])
# similarly for another value of process temp 309.2 K, the model predicts a air temp of 299.05 K

array([[299.05348175]])

In [47]:
#Loading the model from the saved file and using it
file1='lin_pred_maint.sav'
saved_model=pickle.load(open(file1,'rb'))

In [48]:
saved_model.predict([[308]])

array([[297.63615975]])

In [49]:
linear.score(proc_temp,air_temp)
# This provides the R2 value

0.7675637525032576

In [ ]:
# The accuracy is around 77%